version: "3.9"
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-env 
    container_name: dev-env 
    shm_size: '2048m'
    volumes:
      - "${PROJECT_LOCATION}:/root/ProjectDir:rw"
      - "./nvimhelper/dev_config:/root/dev_config:rw"
      - "./nvimhelper/setup_project.py:/root/setup_project.py:rw"
      - "~/.ssh:/root/.ssh:rw"
    networks:
      - nw 
    ports:
      - 127.0.0.1::5901
    devices:
      - nvidia.com/gpu=0
      - nvidia.com/gpu=1
      - nvidia.com/gpu=2
      - nvidia.com/gpu=3
    deploy:
      resources:
        limits:
          cpus: '48'
          memory: 250G  
    working_dir: "/root/ProjectDir"
    command: ["tail", "-f", "/dev/null"]
    cap_add:
      - SYS_ADMIN

networks:
  nw:
    driver: bridge

