version: "3.9"
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-env 
    container_name: dev-env 
    shm_size: '2048m'
    environment:
      - DISPLAY=${DISPLAY}
      - BACKEND_STORE_URI=${BACKEND_STORE_URI}      
      - ARTIFACT_ROOT=${ARTIFACT_ROOT}
    volumes:
      - "${PROJECT_LOCATION}:/root/ProjectDir:rw"
      - "./nvimhelper/dev_config:/root/.config/dev_config:rw"
      - "./nvimhelper/setup_project.py:/root/setup_project.py:rw"
      - "~/.ssh:/root/.ssh:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${ARTIFACT_ROOT}:${ARTIFACT_ROOT}:rw" 
    network_mode: 'host'
    ports:
      - "5000:5000"
    devices:
      - nvidia.com/gpu=0
      - nvidia.com/gpu=1
      - nvidia.com/gpu=2
    deploy:
      resources:
        limits:
          cpus: '48'
          memory: 250G  
    working_dir: "/root/ProjectDir"
    command: ["tail", "-f", "/dev/null"]
    cap_add:
      - SYS_ADMIN

networks:
  nw:
    driver: bridge

